---
  - name : Configure VTP Server
    hosts: SW1
    gather_facts: false

    tasks:
       - name : VTP Server V2 on SW1
         ios_config:
           authorize: yes
           lines:
             - vtp mode server
             - vtp version 2
             - vtp domain company.org
             - vtp password Passw0rd$

       - name: Save SW1 Configuration
         ios_config:
           save_when: modified