---
- name: Configure Trunks on SW1
  hosts: SW1
  gather_facts: false

  tasks:
    - name: Initiate Trunk Mode
      ios_config:
        authorize: yes
        lines:
          - interface range ethernet0/1-2
          - switchport mode trunk
          - exit
          
    - name: Configure Trunks on {{ inventory_hostname }}
      ios_l2_interfaces:
        config:
          - name: Ethernet0/1
            trunk:
              encapsulation: dot1q
              native_vlan: 99
          
          - name: Ethernet0/2
            trunk:
              encapsulation: dot1q
              native_vlan: 99
        state: merged
            
    
    - name: Save Configuration
      ios_config:
        save_when: modified